### ISSUE TITLE
Vagrant: oslo.config version conflict

### ISSUE THREAD

**Issue by armab** [StackStorm/st2express#49] opened 2015-05-05 22:18 UTC
I get the following error during Vagrant provision:

```sh
error: Installed distribution oslo.config 1.9.3 conflicts with requirement oslo.config>=1.11.0
```
Everything is by default, eg. `st2ver=0.9.0`. Just running: `vagrant up`.

More detailed: 
```sh
...
==> st2express: running develop
==> st2express: running egg_info
==> st2express: creating mistral.egg-info
==> st2express: writing dependency_links to mistral.egg-info/dependency_links.txt
==> st2express: writing requirements to mistral.egg-info/requires.txt
==> st2express: writing mistral.egg-info/PKG-INFO
==> st2express: writing top-level names to mistral.egg-info/top_level.txt
==> st2express: writing entry points to mistral.egg-info/entry_points.txt
==> st2express: writing pbr to mistral.egg-info/pbr.json
==> st2express: [pbr] Processing SOURCES.txt
==> st2express: writing manifest file 'mistral.egg-info/SOURCES.txt'
==> st2express: [pbr] In git context, generating filelist from git
==> st2express: warning: no files found matching 'ChangeLog'
==> st2express: warning: no previously-included files matching '*.pyc' found anywhere in distribution
==> st2express: writing manifest file 'mistral.egg-info/SOURCES.txt'
==> st2express: running build_ext
==> st2express: Creating /opt/openstack/mistral/.venv/lib/python2.7/site-packages/mistral.egg-link (link to .)
==> st2express: Adding mistral 0.0.5.dev689 to easy-install.pth file
==> st2express: Installing mistral-db-manage script to /opt/openstack/mistral/.venv/bin
==> st2express: Installing mistral-server script to /opt/openstack/mistral/.venv/bin
==> st2express:
==> st2express: Installed /opt/openstack/mistral
==> st2express: Processing dependencies for mistral==0.0.5.dev689
==> st2express: error: Installed distribution oslo.config 1.9.3 conflicts with requirement oslo.config>=1.11.0
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
-----

`>=1.11.0` is coming from: https://github.com/stackforge/mistral/blob/master/requirements.txt#L13 ?

Most probably I should fill this bugreport under `st2` repo. Still looks like it's good place here to reproduce.

**Comment by DoriftoShoes** [comment] 2015-05-05 22:25
We were able to repro on our end.  Looking in to this now.  Thanks!

**Comment by jfryman** [comment] 2015-05-06 15:00
Looks like a dependency pinning issue. We fixed with https://github.com/StackStorm/st2express/issues/49, and are going to discuss long-term.

**Closed by jfryman** 2015-05-06 15:00 UTC

**Comment by Kami** [comment] 2015-05-06 15:18
Yep, I also just went ahead and confirmed the fix.

@armab - the issue has been fixed. Can you please go ahead and re-run `vagrant provision`? And if you encounter any more problems, don't hesitate to contact us.

**Comment by armab** [comment] 2015-05-06 15:32
Yes, it worked. (At the moment of @Kami message I was in provisioning state)

Thanks guys for fast reaction!
